### PR TITLE
typo, bg fix

### PR DESCRIPTION
**Pull request by spookybear0**

### CODE REVIEW

**Review by Altenhh — COMMENTED** [review]
This doesn't really follow the design all that well. There's a gradient covering the entire background (0, 1 opacity black) that goes 90% of the entire webpage. (see https://github.com/gd-star-pp/website/blob/master/assets/less/index.less#L23-L45).

Another question I have, what's the issue with the current background?

**Review by ElectroFlameOfficial — COMMENTED** [review]
don't see any necessary change here.

**Comment by spookybear0** [comment]
For me, it fixed the background on all resolution monitors.

**Comment by ElectroFlameOfficial** [comment]
i'll keep the pr open but i don't think we'll use it *yet*

**Comment by spookybear0** [comment]
> This doesn't really follow the design all that well. There's a gradient covering the entire background (0, 1 opacity black) that goes 90% of the entire webpage. (see https://github.com/gd-star-pp/website/blob/master/assets/less/index.less#L23-L45).
> 
> Another question I have, what's the issue with the current background?

I like the current bg, but it's too wide to be a background. I wanted to fix the background being too big. but oddly, the background is correct now.

**Pull request closed without merging**
